spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: debug